import { Inter } from "next/font/google";
import "./globals.css";
import Header from '../app/Header/page'
import Footer from '../app/Footer/page'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Creative Agency",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
