import "./globals.css";
import Header from "../app/Header/page";
import Footer from "../app/Footer/page";
import { Montserrat } from "next/font/google";

export const metadata = {
  title: "Creative Agency",
  description: "Generated by create next app",
};
const montserrat = Montserrat({
  weight: ["700"],
  subsets: ["latin"],
  preload: false,
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
